repos:
  # Standard Hooks
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.2.0
    hooks:
      - id: check-symlinks
      - id: check-yaml
        args: ["--allow-multiple-documents"]
      # - id: double-quote-string-fixer
      - id: forbid-new-submodules
  # Linting & Formatting (Disabled)
  # - repo: https://github.com/astral-sh/ruff-pre-commit
  #   # Ruff version.
  #   rev: v0.8.4
  #   hooks:
  #     # Run the linter.
  #     - id: ruff
  #       args: [ --fix ]
  #     # Run the formatter.
  #     - id: ruff-format
  - repo: local
    hooks:
      - id: make-lint
        name: make-lint
        entry: make
        args: ["lint"]
        language: system
      
  # Security
  - repo: https://github.com/gitleaks/gitleaks
    rev: v8.22.0
    hooks:
      - id: gitleaks
